# Site settings
title: GoBraves Blog
header-img: img/home-bg2.jpg
description: "To be my hero"
baseurl: ""
url: "http://yourdomain.com"
github_username:  gobraves
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
